//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public int UserID { get; set; }
        public int RateID { get; set; }
        public string AddressSetup { get; set; }
        public string PlaceSetup { get; set; }
        public string ConnectionPoint { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual User User { get; set; }
    }
}
